# Generated by Django 4.2 on 2023-04-06 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.PositiveIntegerField(max_length=1)),
                ('list_number', models.PositiveIntegerField(max_length=2)),
                ('student_id', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer1a', models.PositiveIntegerField(max_length=2)),
                ('answer1b', models.PositiveIntegerField(max_length=2)),
                ('answer2a', models.PositiveIntegerField(max_length=2)),
                ('answer2b', models.PositiveIntegerField(max_length=2)),
                ('answer3a', models.PositiveIntegerField(max_length=2)),
                ('answer3b', models.PositiveIntegerField(max_length=2)),
                ('answer4a', models.PositiveIntegerField(max_length=2)),
                ('answer4b', models.PositiveIntegerField(max_length=2)),
                ('correctAnswerA', models.PositiveIntegerField(max_length=2)),
                ('correctAnswerB', models.PositiveIntegerField(max_length=2)),
                ('student_answerA', models.PositiveIntegerField(max_length=2)),
                ('student_answerB', models.PositiveIntegerField(max_length=2)),
                ('responseTime', models.PositiveIntegerField(max_length=3)),
                ('level', models.PositiveIntegerField(max_length=1)),
                ('difficulty', models.PositiveIntegerField(max_length=1)),
                ('dateTime', models.DateTimeField(auto_now_add=True, null=True)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.student')),
            ],
        ),
    ]
